version: "3.1"
services:
  database:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=estacionamento"
    ports:
      - 5433:5432
    volumes:
      - pg-data:/var/lib/postgresql/data  
volumes:
  pg-data:
  
